### ISSUE TITLE
TypeError: result.slice is not a function

### ISSUE THREAD

**Issue by MichaelMausbach** [mykle1/MMM-BMW-CC#2]
Got the follwing issue when running the MBW-CC module.

[2020-12-16 07:36:31.093] [ERROR]  Whoops! There was an uncaught exception...
[2020-12-16 07:36:31.095] [ERROR]  TypeError: result.slice is not a function
    at Request._callback (/home/pi/MagicMirror/modules/MMM-BMW-CC/node_helper.js:44:33)
    at Request.self.callback (/home/pi/MagicMirror/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Following settings were used:
	{
			disabled: false,
			module: "MMM-BMW-CC",
			position: "bottom_bar", // designed for bottom_bar(best) thirds should be good too
			config: {
				apiKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxx", // Get at https://www.climacell.co/weather-api/pricing/
				ownTitle: "Current Conditions",
				tempUnits: "C", // us = F or si = C
				lat: '50.000000', // Your latitude
				lon: '8.000000', // Your longitude
				css: "2", // 1-6
				playSounds: "no",
				useHeader: false, // true if you want a header
				header: "Your header",
				maxWidth: "100%",
				updateInterval: 5 * 60 * 1000,
			}
		},

**Comment by cowboysdude** [comment]
Pull request sent, should fix this problem.

**Comment by mykle1** [comment]
Yo CBD!

Thanks for taking the initiative and contributing. Lots of people want stuff done but very few actually volunteer to help. In your case, you just sent me the PR with the work already done. I really appreciate that. It's hard to keep up as you well know.

Peace!

**Comment by Dresch360** [comment]
I'm having the same issue as MichaelMausbach "TypeError: result.slice is not a function"  - I've done a clean install, but still get the same error message. Any help would be greatly appreciated.

[2021-01-14 15:26:11.909] [LOG]    Whoops! There was an uncaught exception...
[2021-01-14 15:26:11.910] [ERROR]  TypeError: result.slice is not a function
    at Request._callback (/home/pi/MagicMirror/modules/MMM-BMW-CC/node_helper.js:44:33)
    at Request.self.callback (/home/pi/MagicMirror/modules/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/home/pi/MagicMirror/modules/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)

{
 disabled: false,
 module: "MMM-BMW-CC",
 position: "top_bar", // designed for bottom_bar(best) thirds should be good too
  config: {
   apiKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",//Get at https://www.climacell.co/weather-api/pricing/
   ownTitle: "Current Conditions",
   tempUnits: "us", // us = F or si = C
   lat: '30', // Your latitude
   lon: '-100', // Your longitude
   css: "2", // 1-6
   playSounds: "no",
   useHeader: false, // true if you want a header
   header: "Your header",
   maxWidth: "100%",
   updateInterval: 5 * 60 * 1000,
   }
},

**Comment by mykle1** [comment]
Not really sure what's going on here. I just downloaded a fresh install and it fires right up for me. I can better assist you on the MagicMirror forum if you create a new topic in the Troubleshooting category.

Hmmm. I just used your config entry with my API key and it fired right up. Make absolutely sure your api key is entered correctly. 
Have you modified any of this modules files?
Last, if you don't mind, I can try your api key and see if it's working. Don't post it here because this is not private. You can send it to me on the MagicMirror forum in a chat and I will test it for you

**Comment by dresch27** [comment]
Hi Mykle,

Thank you very much for your response and I really appreciate it. Also, my apologies for the additional issues posts.

Below are two separate new API keys I've tried:

CIl0JSGP61kJT21kOOQS71DDYeonzehY
MgQwrNshricz6ugVNiMi6qn67YoFrwzJ



________________________________

**Comment by Dresch360** [comment]
Thank you very much for your response and I really appreciate it. Also, my apologies for the additional issues posts. Yeah, if you try to use a recent NEW API key, it doesn't work and you get the  "TypeError: result.slice is not a function" error. Would be great to send you my API keys. No modifications were made to the module.

**Comment by mykle1** [comment]
Ok, so. I now know what the problem is. First let me apologize. My API key is still working so I thought there must be some user error. I was wrong. Climacell is no longer issuing v3 api keys (which the module uses). The new keys are for the v4 api. 

What does this mean? It means I will have to make some time to modify the module to use with the new v4 api, if not a complete rewrite of the module. This also means it will be some time before I have a chance to do so. 

Again, I apologize for not realizing the issue sooner

**Comment by mykle1** [comment]
In the meantime, if you so choose, my MMM-BMW-OW module has the identical display format and uses the free openweather api key. Anyway . . .

**Comment by Dresch360** [comment]
No problem at all and thank you again for getting back to me and for letting me know. I'll check out the MMM-BMW-OW module.

**Comment by mykle1** [comment]
Ok, so, the updated module now works with the new api keys. Sorry about the delay. I was using an older v3 api key. It still works but will be closed soon. The new api keys work with the new version 4 of the api itself. This module has been updated to make use of the new v4 api.

My apologies

**Comment by Dresch360** [comment]
Thank you so much for taking the time to resolve this! I really appreciate all of the work and dedication you've put into this, as well as your other modules.
